Vagrant.configure("2") do |config|
  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "bento/ubuntu-22.04"

    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    config.vm.synced_folder "./data", "/vagrant_data"
    mysql.vm.network "public_network", type: "DHCP"
    mysql.vm.provision "shell", path: "provision/my_sql.sh"
  end
end
