global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["3.121.214.201:9100", "18.184.151.148:9100", "18.184.125.7:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets: ["18.184.151.148:9101", "18.184.125.7:9101"]

rule_files:
  - prometheus_alerts_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 3.121.214.201:9093
