apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-ht-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alex-ht
  template:
    metadata:
      labels:
        app: alex-ht
    spec:
      containers:
      - name: app
        image: nginx:1.24.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: alex-ht
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


