
apiVersion: v1
kind: Pod
metadata:
  name: romang-test
  labels:
    author: RomanGrekov
spec:
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: ebs-gp2-claim
  containers:
    - name: main
      image: ubuntu
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - mountPath: "/myfolder"
          name: test-vol