apiVersion: apps/v1
kind: Deployment
metadata:
  name: romang-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: romang-test
  template:
    metadata:
      labels:
        app: romang-test
    spec:
      containers:
      - name: app
        image: nginx:1.24.0
        #command: ["/app/start.sh"]
        ports:
        - containerPort: 80

