apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: alpine  # если пользователь в качестве имени образа указал "alpine".
    command: ["tail", "-f", "/dev/null"]

