Vagrant.configure("2") do |config|
  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.box = "bento/ubuntu-22.04"
    prometheus.vm.hostname = "prometheus"
    
    prometheus.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.synced_folder "./data", "/vagrant_data"
    prometheus.vm.network "public_network", type: "static", ip: "192.168.31.10" 

    prometheus.vm.provision "shell", path: "provision/install_prometheus_VM1.sh"

  end

  config.vm.define "nodeexporter" do |nodeexporter|
    nodeexporter.vm.box = "bento/ubuntu-22.04"
    nodeexporter.vm.hostname = "nodeexporter"
    
    nodeexporter.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    nodeexporter.vm.network "public_network", type: "static", ip: "192.168.31.11" 
    
    nodeexporter.vm.provision "shell", path: "provision/install_nodeexporter_VM2.sh"

  end
end