Vagrant.configure("2") do |config|

  config.vm.define "JenkinsServer" do |server|
    server.vm.box = "bento/ubuntu-22.04"  
    server.vm.hostname = "jenkins-server"  
    server.vm.network "public_network", ip: "192.168.31.210"  
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  
      vb.cpus = 1  
    end
    server.vm.provision "shell", path: "provision/jenkins.sh"
  end

  config.vm.define "JenkinsWorker" do |worker|
    worker.vm.box = "bento/ubuntu-22.04"  
    worker.vm.hostname = "jenkins-worker"  
    worker.vm.network "public_network", ip: "192.168.31.211"  
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  
      vb.cpus = 1  
    end
    worker.vm.provision "shell", path: "provision/worker.sh"
  end
  config.vm.synced_folder "./data", "/vagrant_data"
end