version: '3'

services:
  python_app:
    build: ./app
    container_name: python_app
    networks:
      - my_network

  mysql_application:
    build: ./mysql
    container_name: mysql_application
    networks:
      - my_network
    ports:
      - "3306:3306"

networks:
  my_network:

