- hosts: all
  become: yes
  tasks:
    - name: Update pacheges
      shell: |
        sudo apt update
    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present
    - name: Copy nginx configuration file
      copy:
        src: "./nginx/nginx.conf"
        dest: "/home/ubuntu/nginx.conf"
        owner: root
        group: root
        mode: "0777"
    - name: Install Docker CLI
      apt:
        name: docker-compose
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull
    - name: Run nginx Docker container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "8080:80"
        volumes:
          - "/home/ubuntu/nginx.conf:/etc/nginx/nginx.conf"
        